fub_general:
    resource: "@FUBGeneralBundle/Resources/config/routing.yml"
    prefix:   /

fub_user:
    resource: "@FUBUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"